### PR TITLE
Update package to reflect new 2.2.0 namespace

### LINKED ISSUE #39: fix EML 2.2.0 namespace
currently the namespace is listed as eml://ecoinformatics.org/eml-2.2.0, but I believe it should be https://eml.ecoinformatics.org/eml-2.2.0

### PR DESCRIPTION
**Pull request by amoeba**
Between the last sync and the final 2.2.0 release, we:

- Changed the EML namespace from `eml://eml.ecoinformatics.org/eml-2.2.0` to `https://eml.ecoinformatics.org/eml-2.2.0` to move forward with a more standard namespace scheme since everyone minting their own custom schemes never took off and we centralized around HTTP(S).
- Added a few attributes to the `annotation` element

This PR basically:

- Updates XSDs to match 2.2.0 released versions of them
- Switches the default schema version to 2.2.0
- Updates all test docs to the new namespace
- Factors out previously-hardcoded references to `eml://...` to be dynamic based up on version, using the new `https://...` prefix when appropriate.

Other stuff I ended up doing:

- Fixing breakage in test.sh caused by `jq`
- Rebuilding pkgdown site

Could use a quick sanity check as it's quite a lot of change.

Closes #39.

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks for cranking through this  - yeah this one must have been a bit of a beast to change with so many places that namespace is hardwired in test and example files.  I've skimmed through all the changes and looks good!  (some whitespace trimming makes them look even more sweeping than they really are, but oh well).  

Only thing -- I don't think you created an entry in NEWS.md describing this change yet? Can you bump the package version to `0.2.1` and add an entry about the changed namespace?  I guess this is technically a breaking change, and maybe it should be more of a major version bump -- though calling this `1.0.0` seems a bit weird -- I don't fully buy into semantic versioning since any change can break something for someone...  What do you think?

Also, is this a good point to cut a new release to CRAN or can you think of any other things we might want to tackle in the near-term first?

**Comment by jeanetteclark** [comment]
Thanks for this @amoeba.

Before cutting the new release, we might want to switch back to setting the default EML version to 2.2.0 now that this is officially out. I created an issue requesting the switch to 2.1.1 until 2.2.0 got released.

**Comment by cboettig** [comment]
p.s. @amoeba Just for reference, ropensci's [docs server](https://github.com/ropensci/docs) builds pkgdown automatically now as part of the nightly checks, so no need to build it locally.  Should probably drop it from the repo here.  

See https://docs.ropensci.org/emld/ for the auto-generated docs and http://packages.ropensci.org/job/emld/ for the Jenkins job log that creates these.  

All 🎩 work from @jeroen 😄

**Comment by amoeba** [comment]
Slick, nice work @jeroen !

**Pull request merged**
